# Generated by Django 6.0.7 on 2026-07-08 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Sobrenome'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
    ]
