# Generated by Django 6.1.1 on 2026-10-05 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('sobrenome', models.CharField(blank=True, default='', max_length=120, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('sexo', models.CharField(blank=True, default='', max_length=1, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(blank=True, default='', max_length=14, verbose_name='CPF')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=45, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, default='', max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, default='', max_length=60, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, default='', max_length=60, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=45, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=45, verbose_name='Estado')),
                ('cep', models.CharField(max_length=20, verbose_name='CEP')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='usuarios.cliente')),
            ],
        ),
    ]
